### ISSUE TITLE
No text displaying

### ISSUE THREAD

**Issue by jsteel44** [geommer/yabar#9] opened 2016-03-15 14:02 UTC
Hi,
Using the example config I don't see any text in the bar. I have ttf-droid and ttf-font-awesome installed which seem to be the fonts it wants, but I've also tried specifying other fonts with no luck.
I'm on Arch with herbstluftm. I just submitted packages to the AUR btw.

This doesn't show anything either:

```
bar-list: ["bar1"];
bar1: {
    block-list: ["block1"];
    block1: {
      exec: "date";
    }
}
```

**Comment by geommer** [comment] 2016-03-15 14:23
Thank you for the AUR. For your issue, that is because you did not add a `fixed-size` entry which defines the width of the block, and this falls back to a default value of zero and thus no text is displayed. I admit this was stupid so I changed the default value to 80 but you are encouraged to override it with a more appropriate value.

**Comment by jsteel44** [comment] 2016-03-15 14:24
Sorry, still doesn't show any text for me in 0.1.0-5-g5893a74

**Comment by geommer** [comment] 2016-03-15 14:30
Try to add the line `type: "periodic"` and tell me if it works.

**Comment by jsteel44** [comment] 2016-03-15 14:33
I'm using this https://github.com/geommer/yabar/blob/master/examples/example.config which has "type: periodic" for the date block. The config I pasted was just a test with a minimal config, I am using the example config in your repo. Thanks

**Comment by SageEx** [comment] 2016-03-15 16:34
Same here, using AUR package and using the sample config.

**Comment by z1lt0id** [comment] 2016-03-16 09:30
I am also having this issue.  I've attached a screenshot of my desktop as well as the script I've created.
![Uploading 2016-03-16-202510_3440x1440_scrot.png…]()
```
bar-list = ["topbar"];
topbar:{
        font: "Source Sans Pro 8, FontAwesome Bold 9";
        block-list: ["cpu", "ram"];
        position: "top";
        gap-vertical: 15;
        gap-horizontal: 1270;
        height: 30;
        width: 500;
        slack: 5;
        background-color-rgb: 0x20292d;
        underline-size: 2;
        overline-size: 0;
        slack-size: 4;
        cpu:{
             exec: "cpu";
             align: "left";
             fixed-size: 120;
             type: "periodic";
             interval: 1;
             foreground-color-rgb:0x60867f;
             underline-color-rgb:0xc4c4b5;
             overline-color-rgb:0xc4c4b5;
        }
        ram:{
             exec: "free -m | awk 'NR==2 {print $3}'";
             align: "right";
             fixed-size: 120;
             type: "periodic";
             interval: 1;
             foreground-color-rgb:0xa66959;
             underline-color-rgb:0xc4c4b5;
             overline-color-rgb:0xc4c4b5;
        }
}
```

**Comment by geommer** [comment] 2016-03-16 16:10
@z1lt0id I don't have your cpu script but I added your ram block to my config and it works well for me.

I think your horizontal gap is so large. Try to have a small value. Please have a look again at README to understand what happens when you use `gap-horizontal` combined with `width`.

**Comment by z1lt0id** [comment] 2016-03-16 23:06
@geommer Thanks for the response.  I'll have a look.

**Comment by jsteel44** [comment] 2016-03-18 14:00
Just in case this has been forgotten (as it is closed for some reason) any update on this? Just tried the latest from git but still no text showing.

**Comment by geommer** [comment] 2016-03-18 14:09
Hi @jsteel44, I didn't forget it, the config in your first comment is invalid. You must specify a `type` entry for every block you add. I closed it because I thought it was because the default text width was zero at the time which also makes your block width is zero and consequently no text is displayed. Try to add `type: "periodic"` to your config and tell me if it still not working.

**Comment by jsteel44** [comment] 2016-03-18 14:35
I said I was using the example config provided. What I pasted was something I tried but it doesn't work *either*. I then said:

> I'm using this https://github.com/geommer/yabar/blob/master/examples/example.config which has "type: periodic" for the date block. The config I pasted was just a test with a minimal config, I am using the example config in your repo. Thanks

**Comment by geommer** [comment] 2016-03-18 14:51
@jsteel44 That is okay. If I knew a way to reopen a closed issue, I would have done it. I just need to know what you see. Is the bar drawn with no text or there is no bar drawn at all?

I suspect this may be because your screen depth does not support 32-bit which is the current only supported depth. I would like to see what `xdpyinfo` command shows to you.

**Comment by jsteel44** [comment] 2016-03-18 14:59
https://bpaste.net/show/97c788d1c0fb
I see the bar, just no text in it. Thanks

**Comment by geommer** [comment] 2016-03-18 16:48
I managed to reopen the issue. I really can't figure out what the problem is because the lack of using extensive logs in my code (which will be fixed within the incoming days). The example.config works fine for me so I would like to know:

* When you invoke `yabar` in your terminal, does it exit immediately and shows some dump (it may happen even with the bar keeps being drawn because the x cleanup function has not been invoked) or yabar works just fine until you kill it?
* Do you use compton or some other compositor?
* Do you have `xtitle` installed which is used in example.config? you can install it using `yaourt -s xtitle`.
* Could you please git pull your code and build it again?

**Comment by carnager** [comment] 2016-03-19 07:19
same issue here. i see the bar, but no text in it... also installed from AUR

**Comment by geommer** [comment] 2016-03-19 09:45
Jesus! I think it is now fixed. This should face only who installs it from AUR due to the makepkg gcc flag `-O2`. If I add it to my makefile the problem appears. For now, I added `-O0` to makefile just to override the `-O2` flag added by makepkg. This optimization seems to not return the correct visualtype value in `ya_get_visualtype()`.

**Comment by jsteel44** [comment] 2016-03-19 10:36
Yes looks good now thanks!

**Comment by carnager** [comment] 2016-03-19 10:58
hmm, not for me

**Comment by geommer** [comment] 2016-03-19 11:08
Guys, please install the git version from AUR in order to be synced with the commits.

**Closed** 2016-03-21 04:52 UTC
