### ISSUE TITLE
volume block doesn't with audio output change

### ISSUE THREAD

**Issue by SavoyRoad** [geommer/yabar#135] opened 2017-03-19 00:44 UTC
When switching between my computer speakers and headphones, the volume block does not update with the change.  For example, if I have the headphone volume set to 75%, the block will show the correct value.  When I unplug them, alsamixer etc. update and show the volume level of the speakers, let's say 45%, but that only updates if I restart yabar.

**Comment by jacksgt** [comment] 2017-03-19 09:37
Are you using PulseAudio or only ALSA? Also, please post your configuration of at least the volume block.
Finally, what version of yabar are you running? (You can check with `yabar -v`)

**Comment by SavoyRoad** [comment] 2017-03-19 13:48
Using PulseAudio with yabar v0.4.0-91-g8f6039b

```
 volume: {
	exec: "YABAR_VOLUME";
	interval: 1;
	internal-option1: "default"; # device
	internal-option2: "Master 0"; #Mixer index (separated by space)
	internal-option3: " "; #characters to display when sound is on or off
	internal-suffix: "%";	 

	align: "right";
	fixed-size: 60;
	type: "periodic";

	background-color-rgb: 0x81A2BE;
	foreground-color-rgb: 0x373B41;
     }
```

**Comment by jacksgt** [comment] 2017-03-19 15:53
Could you run yabar from the command line and watch for any error messages? (E.g. `unable to open mixer`, `unable to attach mixer to device`, `unable to register mixer` or `unable to load mixer elements`)

**Comment by jacksgt** [comment] 2017-03-19 16:15
I can not reproduce the issue with `yabar v0.4.0-98-g884ca23` (current master HEAD). I'm running yabar with PulseAudio (ALSA backend) on Debian unstable (sid).
When I'm switching the output source, the block updates (after a few seconds) with the correct percentage, and volume changes are also reflected.
```conf
    ya_volume:{
        exec: "YABAR_VOLUME";
        align: "right";
        interval: 5;
        internal-option1 : "default"; # device
        internal-option2 : "Master 0"; # Mixer index (separated by a semicolon)
        internal-option3 : " "; # characters to display when sound is on or off (sep
arated by a space)
        internal-suffix: "%";
        underline-color-rgb:0x391113e;
        command-button1: "pavucontrol || alsamixer";
    }
```

**Comment by SavoyRoad** [comment] 2017-03-19 16:27
I get no error messages when running from the command line.  I have the same audio setup as you and I'm currently on Debian testing, and both alsamixer/pavucontrol correctly show the change.  Here's my `amixer info` output if it helps any.

```
Card default 'pulse'/'PulseAudio'
  Mixer name	: 'PulseAudio'
  Components	: ''
  Controls      : 4
  Simple ctrls  : 2
```

**Comment by jacksgt** [comment] 2017-03-19 16:29
Weird, we have almost the same setup and my `amixer info` output also looks exactly the same.

**Comment by SavoyRoad** [comment] 2017-03-19 16:31
Usually in these cases I blame quirks on the fact that I'm running on a 2010 macbook pro, but I don't think that would change anything based on our setups.

**Comment by jacksgt** [comment] 2017-03-19 16:43
Nah, this seems to be some software glitch, since alsamixer works fine for you.
(I have one, too: ALSA reports more than 100% volume for my speakers, but not for the headphones :D)

**Comment by SavoyRoad** [comment] 2017-03-19 17:01
I'll keep an eye out for any fixes down the road.  Alsamixer doesn't update with the output change unless I rerun it, so it may be an issue with that.  

It's not a big deal at least, most of the time my speaker output is muted anyway!

**Comment by jacksgt** [comment] 2017-03-19 17:27
> Alsamixer doesn't update with the output change unless I rerun it, so it may be an issue with that.

Ah, there is the difference. For me alsamixer updates automatically (in this clip I just plug in and out my headphones a few times):
https://asciinema.org/a/4pj272zassjem7055zzzw2fun
What version of the package alsa-utils are you running?
```shell
$ apt show alsa-utils | grep Version
Version: 1.1.3-1
```

**Comment by SavoyRoad** [comment] 2017-03-19 17:47
Ah, see that doesn't happen with `alsamixer`, but `pavucontrol` automatically changes.  I'm running `v 1.1.3-1` as well though.

**Comment by jacksgt** [comment] 2017-03-21 19:51
As this isn't a yabar problem, I'll close this issue now.
However, I think you should open a Debian bug report for PulseAudio.

**Closed by jacksgt** 2017-03-21 19:51 UTC
